### ISSUE TITLE
Better website for Pokemon-PythonRed

### ISSUE THREAD

**Issue by Ravanger101** [Pokemon-PythonRed/Pokemon-PythonRed.github.io#1]
I would like to make a Website for this game, I will make a website in CSS, HTML and Javascript to make look cool. As the animations would look good. The current website only re-directs to It's Main page. I just want some ideas, Issues and comments to make it.
If anyone wants to see my work here it is:
**My website**: https://ravanger101.github.io/DragonRealmsWebsite/
**XPV website made by me**: https://xpvilion.github.io/XPV/
Thanks, for Reading this
Web Developer, Game Dev and a Gamer
**Aryan**
panther2008aryan101@gmail.com

**Comment by riverpaper** [comment]
Sounds cool! I'd be happy to let you make the website.

I don't know if it's possible, but could you make the site display the documentation from [the `README`](https://github.com/Pokemon-PythonRed/Pokemon-PythonRed#readme)?

Sorry for the delayed response, it seems I don't get notifications for Organisation activity.

**Comment by Ravanger101** [comment]
Sure, I am on it
